apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
# every persistant volume is bound to a single persistent volume (PVC -> PV)
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500Mi