apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-log-1
# every persistant volume is bound to a single persistent volume (PVC -> PV)
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi