apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec: 
  containers:
    - name: nginx
      image: nginx:alpine
      volumeMounts:
        - mountPath: /var/www/html
          name: local-persistent-storage
  volumes:
    - name: local-persistent-storage
      persistentVolumeClaim:
        claimName: local-pvc