apiVersion: v1 
kind: Pod
metadata:
  name: yellow
spec:
  initContainers:
    - name: red-initcontainer
      image: busybox
      command:
        - sleep
        - "20"
  containers:
  - name: lemon
    image: busybox
    command:
      - sleep
      - "1000"
  - name: gold
    image: redis

